### ISSUE TITLE
Downloads completely stopped working

### ISSUE THREAD

**Issue by httpete** [halcyon/asdf-maven#16]
It has been fine, but they must have moved some repository location, no list-all or install cmds work.

This cmd does hang for me:

```
curl -s https://repository.apache.org/content/repositories/snapshots/org/apache/maven/apache-maven/maven-metadata.xml
```

```
[ps893826@ps893826-pcdev react-components]$ curl -v -s https://repository.apache.org/content/repositories/snapshots/org/apache/maven/apache-maven/maven-m
etadata.xml
*   Trying 65.109.119.155:443..
```

**Comment by httpete** [comment]
```
curl: (28) Failed to connect to archive.apache.org port 443: Connection timed out
```

**Comment by samhaque** [comment]
I had to manually edit the install script with the following change:
```
local base="https://archive.apache.org/dist/maven"
```
became:
```
local base="https://dlcdn.apache.org/maven"
```
and now the Install works again.

**Comment by samhaque** [comment]
@halcyon for your awareness, asdf and mise both projects are using your plugin and currently all downloads of maven are blocked due to this base url changing.

**Comment by halcyon** [comment]
> ```
> curl: (28) Failed to connect to archive.apache.org port 443: Connection timed out
> ```

@samhaque @httpete 
Interestingly the old URL is still functioning for me:
```bash
± % curl -s https://repository.apache.org/content/repositories/snapshots/org/apache/maven/apache-maven/maven-metadata.xml                                
<?xml version="1.0" encoding="UTF-8"?>
<metadata modelVersion="1.1.0">
  <groupId>org.apache.maven</groupId>
  <artifactId>apache-maven</artifactId>
  <versioning>
    <latest>4.0.0-beta-2-SNAPSHOT</latest>
    <release></release>
    <versions>
      <version>3.7.0-SNAPSHOT</version>
      <version>3.8.9-SNAPSHOT</version>
      <version>3.9.10-SNAPSHOT</version>
      <version>4.0.0-alpha-1-SNAPSHOT</version>
      <version>4.0.0-alpha-6-SNAPSHOT</version>
      <version>4.0.0-alpha-11-SNAPSHOT</version>
      <version>4.0.0-alpha-14-SNAPSHOT</version>
      <version>4.0.0-beta-1-SNAPSHOT</version>
      <version>4.0.0-beta-2-SNAPSHOT</version>
    </versions>
    <lastUpdated>20241028185409</lastUpdated>
  </versioning>
</metadata>
```

**Comment by samhaque** [comment]
@halcyon apologies the correct url should be:
```
local base="https://dlcdn.apache.org/maven"
```

To keep things secure during transport, previously I had commented: `http://` instead of `https://`

**Comment by samhaque** [comment]
The apache archive url used to work but no longer loads, I saw in the official maven page the maintainers of maven are moving from the archive url to the apache download cdn url, thought we keep in line with the maven maintainers.

**Comment by brunoselvacj** [comment]
This fix makes installing the older versions impossible. I tested today https://archive.apache.org/dist/maven, and it is working just fine

**Comment by samhaque** [comment]
After further investigation we found our corporate proxy server was blocking connection to apache archive, from public internet the archive url works fine. Please revert the change.

**Comment by brunoselvacj** [comment]
Pull request is ready to me merged with the reverted version

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by brunoselvacj** [comment]
@halcyon
