### ISSUE TITLE
asdf latest maven not working as expected

### ISSUE THREAD

**Issue by cj81499** [halcyon/asdf-maven#9]
```console
> asdf latest maven # expecting latest stable version (`3.8.6` at time of writing)
4.0.0-alpha-2
> asdf latest maven 3 # expecting a version starting with "3"
4.0.0-alpha-2
```

This is also impacting `asdf install maven latest`.

**Comment by cj81499** [comment]
@sboardwell @halcyon

Although the recent changes are an improvement, this still isn't quite working as intended. Now, it always gives the latest stable version (which is an improvement over trying to install a prerelease version!), but it ignores the (optional) version argument 😢.

https://asdf-vm.com/manage/versions.html#show-latest-stable-version

```sh
$ asdf latest maven # expecting latest stable version (3.8.7 @ time of writing)
3.8.7
$ asdf latest maven 3.6 # expecting latest stable version that starts w/ 3.6 (3.6.3 @ time of writing)
3.8.7
```

compare with the Python plugin, which handles this correctly:

```sh
$ asdf latest python
3.11.1
$ asdf latest python 3.10
3.10.9
```

**Comment by sboardwell** [comment]
Oh, let me have a look later today or tomorrow.

**Comment by cj81499** [comment]
I took a quick look at this. I think it's as simple as removing `latest-stable` entirely, since the behavior built into `asdf` should be sufficient.

https://asdf-vm.com/plugins/create.html#optional-scripts:~:text=asdf%20latest%20deduces%20the%20latest%20version%20by%20looking%20at%20the%20last%20version%20printed%20by%20the%20list%2Dall%20callback%2C%20after%20a%20few%20types%20of%20versions%20(like%20release%20candidate%20versions)%20are%20excluded%20from%20the%20output.

**Comment by sboardwell** [comment]
Nice work! Thanks.
